version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even though it's the weekly default
      time: "07:00" # UTC
  - package-ecosystem: "gradle"
    directories:
      - "/java/gradle"
      - "/kotlin/gradle"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even though it's the weekly default
      time: "07:00" # UTC
  - package-ecosystem: "maven"
    directories:
      - "/java/maven"
      - "/kotlin/maven"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even though it's the weekly default
      time: "07:00" # UTC
  - package-ecosystem: "npm"
    directories:
      - "/javascript"
      - "/typescript"
    commit-message:
      prefix: "chore"
    groups:
      gatling:
        patterns:
          - "@gatling.io/*"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even though it's the weekly default
      time: "07:00" # UTC
