version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/java/gradle"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even tough it's the weekly default
      time: "07:00" # UTC
  - package-ecosystem: "maven"
    directory: "/java/maven"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even tough it's the weekly default
      time: "07:00" # UTC
  - package-ecosystem: "gradle"
    directory: "/kotlin/gradle"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even tough it's the weekly default
      time: "07:00" # UTC
  - package-ecosystem: "maven"
    directory: "/kotlin/maven"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even tough it's the weekly default
      time: "07:00" # UTC
